version: "3"

networks:
  luby_projects:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/api/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    networks:
      - luby_projects
    depends_on:
      - mysql
      - dbtest

  mysql:
    build:
      context: ./Docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lottery_tgl_api
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - luby_projects

  dbtest:
    build:
      context: ./Docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root_test
      MYSQL_DATABASE: lottery_tgl_test
    ports:
      - "3456:3306"
    volumes:
      - db-data-test:/var/lib/mysql
    networks:
      - luby_projects    

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
    networks:
      - luby_projects

  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://kafka1:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    networks:
      - luby_projects  
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
    depends_on:
      - kafka1
    networks:
      - luby_projects

volumes:
  db-data:
  db-data-test: