version: "3"

networks:
  luby_projects:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/api/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    networks:
      - luby_projects
    depends_on:
      - mysql
  mysql:
    build:
      context: ./Docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loterry_tgl_api
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - luby_projects

volumes:
  db-data: